import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:saving_app/data/models/category.model.dart';

List<CategoryGroup> builtInCategories = [
  CategoryGroup(id: "c1", type: TransactionType.expense, name: "Tiền nhà", icon: Icons.house,
    subCategories: [
      TransactCategory(id: "c1.1", type: TransactionType.expense, name: "Tiền thuê", icon: Icons.house),
      TransactCategory(id: "c1.2", type: TransactionType.expense, name: "Bảo hiểm thuê nhà", icon: Icons.house),
      TransactCategory(id: "c1.3", type: TransactionType.expense, name: "Sửa chữa", icon: Icons.house),
      TransactCategory(id: "c1.4", type: TransactionType.expense, name: "Nâng cấp", icon: Icons.house),
      TransactCategory(id: "c1.5", type: TransactionType.expense, name: "Đồ gia dụng", icon: Icons.house),
      TransactCategory(id: "c1.6", type: TransactionType.expense, name: "Khác", icon: Icons.house),
    ],
  ),
  CategoryGroup(id: "c2", type: TransactionType.expense, name: "Ăn uống", icon: Icons.food_bank_outlined,
    subCategories: [
      TransactCategory(id: "c2.1", type: TransactionType.expense, name: "Đi chợ", icon: Icons.house),
      TransactCategory(id: "c2.2", type: TransactionType.expense, name: "Ăn hàng", icon: Icons.house),
      TransactCategory(id: "c2.3", type: TransactionType.expense, name: "Café", icon: Icons.house),
      TransactCategory(id: "c2.4", type: TransactionType.expense, name: "Khác", icon: Icons.menu_rounded),
    ],
  ),
  CategoryGroup(id: "c3", type: TransactionType.expense, name: "Di chuyển", icon: CupertinoIcons.bus,
    subCategories: [
      TransactCategory(id: "c3.1", type: TransactionType.expense, name: "Phí phương tiện", icon: Icons.house),
      TransactCategory(id: "c3.2", type: TransactionType.expense, name: "Fare", icon: Icons.house),
      TransactCategory(id: "c3.3", type: TransactionType.expense, name: "Sửa chữa", icon: Icons.house),
      TransactCategory(id: "c3.4", type: TransactionType.expense, name: "Đăng kiểm", icon: Icons.house),
      TransactCategory(id: "c3.5", type: TransactionType.expense, name: "Nhiên liệu", icon: Icons.house),
      TransactCategory(id: "c3.6", type: TransactionType.expense, name: "Phí đỗ xe", icon: Icons.house),
    ]
  ),
  CategoryGroup(id: "c4", type: TransactionType.expense, name: "Thiết yếu", icon: CupertinoIcons.bus,
    subCategories: [
      TransactCategory(id: "c4.1", type: TransactionType.expense, name: "Điện", icon: Icons.house),
      TransactCategory(id: "c4.2", type: TransactionType.expense, name: "Nước", icon: Icons.house),
      TransactCategory(id: "c4.3", type: TransactionType.expense, name: "Vệ sinh", icon: Icons.house),
      TransactCategory(id: "c4.4", type: TransactionType.expense, name: "Gas", icon: Icons.house),
      TransactCategory(id: "c4.5", type: TransactionType.expense, name: "Điện thoại", icon: Icons.house),
      TransactCategory(id: "c4.6", type: TransactionType.expense, name: "Truyền hình/Cable", icon: Icons.house),
      TransactCategory(id: "c4.7", type: TransactionType.expense, name: "Internet", icon: Icons.house),
    ],
  ),
  CategoryGroup(id: "c5", type: TransactionType.expense, name: "Giáo dục", icon: CupertinoIcons.bus,
    subCategories: [
      TransactCategory(id: "c5.1", type: TransactionType.expense, name: "Tiền học chính", icon: Icons.house),
      TransactCategory(id: "c5.2", type: TransactionType.expense, name: "Gia sư", icon: Icons.house),
      TransactCategory(id: "c5.3", type: TransactionType.expense, name: "Trường luyện thi", icon: Icons.house),
      TransactCategory(id: "c5.4", type: TransactionType.expense, name: "Khóa học", icon: Icons.house),
      TransactCategory(id: "c5.5", type: TransactionType.expense, name: "Khác", icon: Icons.house),
    ],
  ),
  CategoryGroup(id: "c6", type: TransactionType.expense, name: "Giải trí", icon: CupertinoIcons.bus,
    subCategories: [
      TransactCategory(id: "c6.1", type: TransactionType.expense, name: "Hoạt động", icon: Icons.house),
      TransactCategory(id: "c6.2", type: TransactionType.expense, name: "Sách", icon: Icons.house),
      TransactCategory(id: "c6.3", type: TransactionType.expense, name: "Games", icon: Icons.house),
      TransactCategory(id: "c6.4", type: TransactionType.expense, name: "Vui chơi", icon: Icons.house),
      TransactCategory(id: "c6.5", type: TransactionType.expense, name: "Sở thích", icon: Icons.house),
      TransactCategory(id: "c6.6", type: TransactionType.expense, name: "Phim/Nhạc", icon: Icons.house),
      TransactCategory(id: "c6.7", type: TransactionType.expense, name: "Hoạt động dã ngoại", icon: Icons.house),
      TransactCategory(id: "c6.8", type: TransactionType.expense, name: "Thể thao", icon: Icons.house),
      TransactCategory(id: "c6.9", type: TransactionType.expense, name: "Đồ chơi", icon: Icons.house),
      TransactCategory(id: "c6.10", type: TransactionType.expense, name: "Du lịch", icon: Icons.house)
    ],
  ),
  CategoryGroup(id: "c7", type: TransactionType.expense, name: "Cá nhân", icon: CupertinoIcons.bus,
    subCategories: [
      TransactCategory(id: "c7.1", type: TransactionType.expense, name: "Quần áo", icon: Icons.house),
      TransactCategory(id: "c7.2", type: TransactionType.expense, name: "Vật dụng cá nhân", icon: Icons.house),
      TransactCategory(id: "c7.3", type: TransactionType.expense, name: "Làm đầu", icon: Icons.house),
      TransactCategory(id: "c7.4", type: TransactionType.expense, name: "Trang sức/Phụ kiện", icon: Icons.house),
      TransactCategory(id: "c7.5", type: TransactionType.expense, name: "Thú cưng", icon: Icons.house),
    ],
  ),
  CategoryGroup(id: "c8", type: TransactionType.expense, name: "Sức khỏe", icon: CupertinoIcons.bus,
    subCategories: [
      TransactCategory(id: "c8.1", type: TransactionType.expense, name: "Bảo hiểm y tế", icon: Icons.house),
      TransactCategory(id: "c8.2", type: TransactionType.expense, name: "Khám bệnh", icon: Icons.house),
      TransactCategory(id: "c8.3", type: TransactionType.expense, name: "Thuốc", icon: Icons.house),
      TransactCategory(id: "c8.4", type: TransactionType.expense, name: "Thục phẩm chức năng", icon: Icons.house),
      TransactCategory(id: "c8.5", type: TransactionType.expense, name: "Khác", icon: Icons.house),
    ],
  ),
  CategoryGroup(id: "c9", type: TransactionType.expense, name: "Cho đi", icon: CupertinoIcons.bus,
    subCategories: [
      TransactCategory(id: "c9.1", type: TransactionType.expense, name: "Quà", icon: Icons.house),
      TransactCategory(id: "c9.2", type: TransactionType.expense, name: "Quyên góp", icon: Icons.house),
      TransactCategory(id: "c9.3", type: TransactionType.expense, name: "Trả nợ", icon: Icons.house),
      TransactCategory(id: "c9.4", type: TransactionType.expense, name: "Khác", icon: Icons.house),
    ],
  ),
  CategoryGroup(id: "c10", type: TransactionType.expense, name: "Đăng ký", icon: CupertinoIcons.bus,
    subCategories: [
      TransactCategory(id: "c10.1", type: TransactionType.expense, name: "Báo", icon: Icons.house),
      TransactCategory(id: "c10.2", type: TransactionType.expense, name: "Tạp chí", icon: Icons.house),
      TransactCategory(id: "c10.3", type: TransactionType.expense, name: "Memberships", icon: Icons.house),
      TransactCategory(id: "c10.4", type: TransactionType.expense, name: "Khác", icon: Icons.house),
    ],
  ),
  CategoryGroup(id: "c11", type: TransactionType.income, name: "Thu nhập", icon: Icons.currency_pound_sharp,
    subCategories: [
      TransactCategory(id: "c11.1", type: TransactionType.income, name: "Lương", icon: Icons.house),
      TransactCategory(id: "c11.2", type: TransactionType.income, name: "Đầu tư", icon: Icons.house),
      TransactCategory(id: "c11.3", type: TransactionType.income, name: "Cho thuê", icon: Icons.house),
      TransactCategory(id: "c11.4", type: TransactionType.income, name: "Khác", icon: Icons.house),
    ]
  ),
  CategoryGroup(id: "c12", type: TransactionType.transact, name: "Chuyển khoản", icon: Icons.currency_pound_sharp,
    subCategories: [
      TransactCategory(id: "c12.1", type: TransactionType.transact, name: "Trả nợ tín dụng", icon: Icons.house),
      TransactCategory(id: "c12.2", type: TransactionType.transact, name: "Rút tiền mặt", icon: Icons.house),
      TransactCategory(id: "c12.3", type: TransactionType.transact, name: "Tiết kiệm", icon: Icons.house),
      TransactCategory(id: "c12.4", type: TransactionType.transact, name: "Khác", icon: Icons.house),
    ]
  ),
];
